spring:
  application:
    name: traceability-microservice-foodcourt
  data:
    mongodb:
      uri: mongodb+srv://admin:admin@foodcourt.ssff4pq.mongodb.net/foodcourt?retryWrites=true&w=majority&appName=foodcourt